services:
  - mssql2014
before_build:
 - nuget restore
build_script:
- msbuild Employment-Services-System.sln
- ps: |
        $startPath = "$($env:appveyor_build_folder)\Employment-Services-System.Test\bin\Debug"
        $sqlInstance = "(local)\SQL2014"
        $dbName = "TestConnection"

        # replace the db connection with the local instance
        $config = join-path $startPath "Employment-Services-System.Test.dll.config"
        $doc = (gc $config) -as [xml]
        $doc.SelectSingleNode('//connectionStrings/add[@name="TestConnection"]').connectionString = "Server=$sqlInstance; Database=$dbName; Trusted_connection=true"
        $doc.Save($config)

        # attach mdf to local instance
        $mdfFile = "$($env:appveyor_build_folder)\Database\Test\TestConnection.mdf"
        $ldfFile = "$($env:appveyor_build_folder)\Database\Test\TestConnection.ldf"
        sqlcmd -S "$sqlInstance" -Q "Use [TestConnection]; CREATE DATABASE [$dbName] ON (FILENAME = '$mdfFile'),(FILENAME = '$ldfFile') for ATTACH"
 
 
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.3.1\tools\net452\xunit.console.x86.exe" -targetargs:"Employment-Services-System.Test\bin\Debug\Employment-Services-System.Test.dll -noshadow" -filter:"+[*]*-[Employment-Services-System.Test]* -[*]Employment_Services_System.Areas.HelpPage.* -[*]Employment_Services_System.Controllers.* -[*]Employment_Services_System.EmploymentDataContext -[*]Employment_Services_System.Models* -[*]Employment_Services_System.App_Start* -[*]Employment_Services_System.App_Start*" -output:"coverage.xml"
after_test:
 - .\packages\Codecov.1.0.3\tools\codecov.exe -f "coverage.xml"