services:
  - mssql2017
before_build:
 - nuget restore
build_script:
 - msbuild Employment-Services-System.sln
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.3.1\tools\net452\xunit.console.x86.exe" -targetargs:"Employment-Services-System.Test\bin\Debug\Employment-Services-System.Test.dll -noshadow" -output:"coverage.xml"
after_test:
 - .\packages\Codecov.1.0.3\tools\codecov.exe -f "coverage.xml"