//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_image
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public byte[] company_image_image { get; set; }
    
        public virtual company company { get; set; }
    }
}
