//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmploymentDataContext : DbContext
    {
        public EmploymentDataContext()
            : base("name=EmploymentDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<business_stream> business_stream { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<company_image> company_image { get; set; }
        public virtual DbSet<education_detail> education_detail { get; set; }
        public virtual DbSet<experience_detail> experience_detail { get; set; }
        public virtual DbSet<job_location> job_location { get; set; }
        public virtual DbSet<job_post> job_post { get; set; }
        public virtual DbSet<job_post_activity> job_post_activity { get; set; }
        public virtual DbSet<job_post_skill_set> job_post_skill_set { get; set; }
        public virtual DbSet<job_type> job_type { get; set; }
        public virtual DbSet<seeker_profile> seeker_profile { get; set; }
        public virtual DbSet<seeker_skill_set> seeker_skill_set { get; set; }
        public virtual DbSet<skill_set> skill_set { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user_account> user_account { get; set; }
        public virtual DbSet<user_log> user_log { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
