//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_post_activity
    {
        public int user_account_id { get; set; }
        public int job_post_id { get; set; }
        public System.DateTime apply_date { get; set; }
    
        public virtual job_post job_post { get; set; }
        public virtual user_account user_account { get; set; }
    }
}
