//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_post_skill_set
    {
        public int skill_set_id { get; set; }
        public int job_post_id { get; set; }
        public int skill_level { get; set; }
    
        public virtual job_post job_post { get; set; }
        public virtual skill_set skill_set { get; set; }
    }
}
