//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class seeker_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seeker_profile()
        {
            this.education_detail = new HashSet<education_detail>();
            this.experience_detail = new HashSet<experience_detail>();
            this.seeker_skill_set = new HashSet<seeker_skill_set>();
        }
    
        public int user_account_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> current_salary { get; set; }
        public string is_annually_monthly { get; set; }
        public string currency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<education_detail> education_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experience_detail> experience_detail { get; set; }
        public virtual user_account user_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seeker_skill_set> seeker_skill_set { get; set; }
    }
}
