//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_set
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skill_set()
        {
            this.job_post_skill_set = new HashSet<job_post_skill_set>();
            this.seeker_skill_set = new HashSet<seeker_skill_set>();
        }
    
        public int id { get; set; }
        public string skill_set_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_post_skill_set> job_post_skill_set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seeker_skill_set> seeker_skill_set { get; set; }
    }
}
