//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_log
    {
        public int user_account_id { get; set; }
        public System.DateTime last_login_date { get; set; }
        public Nullable<System.DateTime> last_job_apply_date { get; set; }
    
        public virtual user_account user_account { get; set; }
    }
}
