//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_account()
        {
            this.job_post = new HashSet<job_post>();
            this.job_post_activity = new HashSet<job_post_activity>();
        }
    
        public int id { get; set; }
        public int user_type_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string gender { get; set; }
        public string is_active { get; set; }
        public int contact_number { get; set; }
        public string sms_notification_active { get; set; }
        public string email_notification_active { get; set; }
        public byte[] user_image { get; set; }
        public System.DateTime registration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_post> job_post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_post_activity> job_post_activity { get; set; }
        public virtual seeker_profile seeker_profile { get; set; }
        public virtual user_log user_log { get; set; }
        public virtual user_type user_type { get; set; }
    }
}
