//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Services_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int id { get; set; }
        public string job_type { get; set; }
        public string company_name { get; set; }
        public string job_description { get; set; }
        public string street_address { get; set; }
        public Nullable<int> skill_level { get; set; }
        public string skill_set_name { get; set; }
    }
}
